### ISSUE TITLE
How to capture and send multiple button presses

### ISSUE THREAD

**Issue by csmith0289** [dalhundal/sky-remote-web#5]
I'd like to have a go at creating a number of buttons on a web page that would function to input multiple numbers, as such allowing me to change the channel to 620 for example.

The idea being that the most common channels will be easily accessible from the page.

As I'm very new to this, would someone mind telling me if a) its possible to do this, and b) how / where to learn how to do this? there is an example on the remote cli for changing to 101 but I don't fully understand how the code works. any help would be appreciated

**Comment by brunoais** [comment]
Hi.
It is possible.
As you can see, all areas in the image for clicking, have the HTML like:

`onClick="skyButton('channelup'); return false;"`

That is an inline callback (bad code IMO but that's what is there).
Given that, with this HTML (cannot test):
`<button onClick="skyButton('6'); skyButton('2'); skyButton('0'); return false;">620</button>`
should get you going.

**Comment by csmith0289** [comment]
@brunoais   Thank you for getting back to me on this, i'd forgot about asking the question. I'll give it a go tonight. Thank you
